modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="realisticharvest"
version="1.0.0"
displayName="Realistic Harvest"
authors="KhanhRomVN"
description='''Realistic Harvest: A Minecraft mod that adds realistic farming mechanics including soil pH, moisture levels, and crop-specific growth requirements.'''

[[dependencies.realisticharvest]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.realisticharvest]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
